// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: proto/create_folder.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileDownloadService_CreateFolder_FullMethodName = "/downloadFile.FileDownloadService/CreateFolder"
)

// FileDownloadServiceClient is the client API for FileDownloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileDownloadServiceClient interface {
	CreateFolder(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileResponse, error)
}

type fileDownloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileDownloadServiceClient(cc grpc.ClientConnInterface) FileDownloadServiceClient {
	return &fileDownloadServiceClient{cc}
}

func (c *fileDownloadServiceClient) CreateFolder(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, FileDownloadService_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileDownloadServiceServer is the server API for FileDownloadService service.
// All implementations must embed UnimplementedFileDownloadServiceServer
// for forward compatibility.
type FileDownloadServiceServer interface {
	CreateFolder(context.Context, *FileRequest) (*FileResponse, error)
	mustEmbedUnimplementedFileDownloadServiceServer()
}

// UnimplementedFileDownloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileDownloadServiceServer struct{}

func (UnimplementedFileDownloadServiceServer) CreateFolder(context.Context, *FileRequest) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedFileDownloadServiceServer) mustEmbedUnimplementedFileDownloadServiceServer() {}
func (UnimplementedFileDownloadServiceServer) testEmbeddedByValue()                             {}

// UnsafeFileDownloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileDownloadServiceServer will
// result in compilation errors.
type UnsafeFileDownloadServiceServer interface {
	mustEmbedUnimplementedFileDownloadServiceServer()
}

func RegisterFileDownloadServiceServer(s grpc.ServiceRegistrar, srv FileDownloadServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileDownloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileDownloadService_ServiceDesc, srv)
}

func _FileDownloadService_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDownloadServiceServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileDownloadService_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDownloadServiceServer).CreateFolder(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileDownloadService_ServiceDesc is the grpc.ServiceDesc for FileDownloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileDownloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "downloadFile.FileDownloadService",
	HandlerType: (*FileDownloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFolder",
			Handler:    _FileDownloadService_CreateFolder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/create_folder.proto",
}
